### ISSUE TITLE
libva-vdpau-driver crashes with SIGFPE

### ISSUE THREAD

**Issue by dsd** [flatpak/freedesktop-sdk-images#126]
On Endless, the avidemux app fails to launch on systems with the official nvidia driver.

```
Probing for LIBVA...
 [libvaProbe] 08:28:50-373  Probing for libVA support...
 [init] 08:28:50-373  [LIBVA] Initializing LibVA library ...
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/nvidia_drv_video.so
libva info: Found init function __vaDriverInit_0_39
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory

Thread 1 "avidemux3_qt5" received signal SIGFPE, Arithmetic exception.
0x00007fffd8e6ce9a in object_heap_destroy (heap=heap@entry=0xc48320) at object_heap.c:275
275	    for (i = 0; i < heap->heap_size / heap->heap_increment; i++) {
(gdb) bt
#0  0x00007fffd8e6ce9a in object_heap_destroy (heap=heap@entry=0xc48320) at object_heap.c:275
#1  0x00007fffd8e6fc58 in destroy_heap (name=name@entry=0x7fffd8e7711c "buffer", heap=heap@entry=0xc48320, destroy_func=destroy_func@entry=0x7fffd8e6fbb0 <destroy_buffer_cb>, user_data=user_data@entry=0xc481d0) at vdpau_driver.c:138
#2  0x00007fffd8e6fca6 in vdpau_common_Terminate (user_data=0xc481d0, destroy_func=0x7fffd8e6fbb0 <destroy_buffer_cb>, heap=0xc48320, name=0x7fffd8e7711c "buffer") at vdpau_driver.c:126
#3  0x00007fffd8e6fca6 in vdpau_common_Terminate (driver_data=0xc481d0) at vdpau_driver.c:159
#4  0x00007fffd8e70b30 in __vaDriverInit_0_39 (ctx=0xc4bcf0) at vdpau_driver_template.h:537
#5  0x00007fffd8e70b30 in __vaDriverInit_0_39 (ctx=0xc4bcf0) at vdpau_driver_template.h:563
#6  0x00007fffd8e70b30 in __vaDriverInit_0_39 (ctx=0xc4bcf0) at vdpau_driver.c:317
#7  0x00007ffff20a9ffe in va_openDriver (dpy=dpy@entry=0xcd2130, driver_name=driver_name@entry=0xc546b0 "nvidia") at va.c:301
#8  0x00007ffff20aaf27 in vaInitialize (dpy=0xcd2130, major_version=0x7fffffffdd68, minor_version=0x7fffffffdd6c) at va.c:563
#9  0x00007ffff79c43b7 in admLibVA::init(GUI_WindowInfo*) () at /app/lib/libADM_coreLibVA6.so
#10 0x0000000000482c41 in libvaProbe() ()
#11 0x000000000045ad05 in startAvidemux(int, char**) ()
#12 0x000000000044e20f in main ()
```

This bug has been widely reported over the years, e.g. at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=748294

Here is the patch applied by Debian to solve this issue:
https://bugs.freedesktop.org/attachment.cgi?id=142296&action=edit

Please add this patch to org.freedesktop.Sdk (it will need to be included in org.kde.Sdk version 5.11 to solve this app launch issue).

**Comment by dsd** [comment]
This patch has now been included in the newer versions of the freedesktop sdk: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/448
