### ISSUE TITLE
Python2-Tk seems broken

### ISSUE THREAD

**Issue by gasinvein** [flatpak/freedesktop-sdk-images#94]
Tkinter module not working:
```
Python 2.7.12 (default, Feb 17 2018, 16:52:07) 
[GCC 6.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import Tkinter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 39, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: No module named _tkinter
```
I guess it's because `lib-dynload/_tkinter.so` is missing.

**Comment by TingPing** [comment]
I don't think tcl/tk belong in fdo, so you'd need to build it yourself.

**Comment by gasinvein** [comment]
As far as I know, Tkinter is a builtin python's module, so I have to build _python_ myself.

**Comment by TingPing** [comment]
It is a bit unfortunate because of the build time but not overly difficult.
